### ISSUE TITLE
Help needed to use "on" modifier with <ValidatedInput />

### ISSUE THREAD

**Issue by saloniy** [adfinis/ember-validated-form#891]
Hi,
I have recently started updating the packages in our app and updated ember-validated-form from v1.4.2 to v3.0.3.
However, after the update, the "on" modifiers are no longer working on the inputs
```

<ValidatedForm @model={{this.changeset}} as |f|>
<f.input
       @name="someName"
              {{on "input" this.performSomeFuntion }}
              {{on "keyup" this.performAnotherFunction}}
              class="margin-none input-group-field"
            />
</ValidatedForm>
```
The "this.perofrmSomeFunction" and "this.performAnotherFunction" were called, as expected, in v1.4.2. 
Is there any way to achieve the same behaviour with v3.0.3 or higher?

**Comment by derrabauke** [comment]
Hey Saloniy, 

in that case you would have to implement your own `<input />` inside the `<f.input />`
Something like this:
```js
   <f.input  data-test-comment @name='comment' as |fi|>
      <label>
        Comment
      </label>
      <input
        type="text"
        placeholder="Enter comment..."
        class="form-control"
        onchange={{action fi.update value='target.value'}}
        value={{fi.value}}
      >
    </f.input>
```
As you are bumping from v1.4.2 to v3.0.3 I guess the *old fashioned* action helper is still needed in your case. Otherwise delete it. 

See the [Customization](https://adfinis.github.io/ember-validated-form/docs/customization) part in the documentation for more inspiration.

Cheers

**Comment by saloniy** [comment]
Thank you for the help, @derrabauke!
