### ISSUE TITLE
Master is incompatible with node < 18

### ISSUE THREAD

**Issue by oakho** [adfinis/ember-validated-form#965]
Hello, I'm upgrading my ember app to ember-validated-form 6.2.0 but I was missing a crucial feature for it which is not yet released in this commit https://github.com/adfinis/ember-validated-form/commit/b29f4d88133aa58a9613aa9bf9f1f6a2761a7974.

But there is also this commit that was added before https://github.com/adfinis/ember-validated-form/commit/f0bfb1cde862039fce0a315176a577fdedc79d50 that prevents me to install it because ember-validated-form is now using this package https://github.com/adfinis/semantic-release-config which only support node >= 18.
 
Therefore, when I try to install ember-validated-form master I get :
```
error @adfinis/semantic-release-config@4.0.0: The engine "node" is incompatible with this module. Expected version ">= 18". Got "16.18.1"
```

I'm not sure if @adfinis/semantic-release-config is meant to be only compatible with node 18 or this is an error on your side but could you fix this issue. 

I'd gladly help but don't think I can do something on my end.

Thanks.

**Comment by derrabauke** [comment]
Hey @oakho :wave:

We also experienced some pain, after we adapted the new `adfinis/semantic-release-config`. But sadly there was no way back since the old package namesspace (`adfinis-sygroup`) should not be used anymore. We did a lot of updates with the release of the `semantic-release-config` which forced us to bump to `node >=18`. It's a double edged sword... :sweat_smile: It now forced us to update a lot of stuff, which is also good.

So you have two options now:
* Run your `yarn install` (or whatever command) with the `--ignore-engines` flag

**OR**

* Update your stuff to be compatible with node v18. We are also running a couple of `ember v3.28.x` apps on `node v18` although it's not officially supported by `3.28.x` it works nicely.

**Comment by oakho** [comment]
Hey @derrabauke,

Thanks for the explanations and proposed solutions !

I was aware of the ignore engines but for some reason I wasn't able to make it work with our current yarn version, I'll have another try soon as that seemed the most convenient way to solve the issue (it's too risky for us to migrate to node 18).

Until I'm able to do either I ended up overriding the validated-form.hbs file and add the missing stuff.

Thanks again for your answer and this addon !
